export const AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR";
export const AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS";
export const VERIFY_ERROR = "VERIFY_ERROR";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
